#!/bin/bash -e
KCTL_LEVEL=${KCTL_LEVEL:-0}
export KCTL_LEVEL=$((KCTL_LEVEL+1))

pipeseen=""
arr=("$@")
pre=()
post=()
for i in $(seq 0 $#); do 
  elem="${arr[$i]}"
  if [ "$elem" == "!" ] ; then
     pipeseen=true
     ofs=$((i+1))
     prenum=$i
     pre=("${@:0:$ofs}")
     post=("${@:$ofs+1:$#}")
     postnum=$(($# - $i))
     break
  fi
  if [ "$elem" == "-n" -o "$elem" == "--namespace" ] ; then
     prev_ns="${arr[i+1]}"
  fi
  if [ "$elem" == "--context" ] ; then
     prev_ctx="${arr[i+1]}"
  fi
done
if [ ! "${pre[*]}" ] ; then 
   xpre=(${arr[*]})
   pre=(${arr[*]})
   xpost=() 
fi

if [ "${post[*]}" ] ; then
  xpre=()
  xpost=()
  for i in $(seq $ofs $#) ; do 
    elem="${arr[$i]}"
    if [ "$elem" == "!" ] ; then
       dof=$(($i+1))
       len=$(($i-$ofs))
       pipeseen2=true
       xpre=("${arr[@]:$ofs:$len}")
       xpost=("${arr[@]:$ofs+$len+1:$#}")
       break
    fi
  done

  if [ ! "${xpre[*]}" ] ; then 
    xpre=(${post[*]})
    xpost=() 
  fi
fi

export prev_ns
export prev_ctx
if [ "${xpre[*]}" ] ; then

  if [ "$pipeseen" ]; then
    RECONSTRUCT=""
    if [ "$prev_ctx" ] ; then
      RECONSTRUCT="${RECONSTRUCT} --context ${prev_ctx}"
    fi
    if [ "$prev_ns" ] ; then
      RECONSTRUCT="${RECONSTRUCT} -n ${prev_ns}"
    fi
  
    if [ "${arr[0]}" == "api-resources" ] ; then
      LIST=$(kubectl ${pre[*]} --verbs=get,list --no-headers | awk '{ printf("%s_%s_%s\n",$1,$(NF-1),$NF)}')
    else
      LIST=$(kubectl ${pre[*]} -o jsonpath="{range .items[*]}{.kind}{'_'}{.metadata.namespace}{'_'}{.metadata.name}{'\n'}{end}")
    fi
 # -o jsonpath="{range .items[*].spec.containers[*]}{.name}{'\n'}{end}" 
    #echo LIST "$LIST"
    for i in $LIST; do
      #echo $i
      if [ "${arr[0]}" == "api-resources" ] ; then
         resource=$(echo "$i"|awk -F_ '{print $1}')
         nsed=$(echo "$i"|awk -F_ '{print $2}')
         kind=$(echo "$i"|awk -F_ '{print $3}')
         do=$(echo "${xpre[*]}"|sed "s/{{resource}}/$resource/g" | sed "s/{{kind}}/$kind/g" | sed "s/{{nsed}}/$nsed/g")
      else
         kind=$(echo "$i"|awk -F_ '{print $1}')
         ns=$(echo "$i"|awk -F_ '{print $2}')
         name=$(echo "$i"|awk -F_ '{print $3}')
         do=$(echo "${xpre[*]}"|sed "s/{{name}}/$name/g" | sed "s/{{kind}}/$kind/g" | sed "s/{{ns}}/$ns/g")
      fi
      if [ "$xpost" ] ; then
         eval "$do ! ${xpost[*]}"
      else
         eval "$do"
      fi
    done
  else
    #echo "kubectl ${arr[*]}"
    eval "kubectl ${arr[*]}" 
  fi
else
  echo ELSE EVAL
  eval "${arr[*]}"
fi
