#!/usr/bin/env python3
PLUGIN_NAME = "line"
PLUGIN_UNAME = PLUGIN_NAME.upper()
PIPE_CMD_IN = "pipe-cmd-in"
PIPE_GET_IN = "pipe-get-in"
PIPE_KC_IN = "pipe-kc-in"
PIPE_CTX_IN = "pipe-ctx-in"
PIPE_FMT_IN = "pipe-fmt-in"
PIPE_NS_IN = "pipe-ns-in"
PIPE_NSED_IN = "pipe-nsed-in"
PIPE_KIND_IN = "pipe-kind-in"
PIPE_NAME_IN = "pipe-name-in"
PIPE_NOTE_IN = "pipe-note-in"
P_UNKNOWN = "_unknown_"
P_DEFAULT = "_default_"
P_WARNING = "warning"
P_ERROR = "error"
P_CUSTOM_FMT = "custom-format"
P_SHORTCUT = "_"
P_EXEC = "exec"

# # # #
# config get-contexts -> get
# config get-context -> api-resources
# api-resources -> get
# get -> get
# get -> exec
# # # # # DOCS
# all commands render command input options/switches for context cmd['ctx'], namespace cmd['ns'] and
# get command can render cmd['kind'] and if present cmd['name'] (object name if present)
# not all commands use, so none of cmd_* are used in config_get-contexts
# * api-resources uses cmd['ctx'] and cmd['ns'] if present in command line to pass those via #pipe
# * get: uses cmd['ctx']/cmd['ns']/cmd['kind']/cmd['name'] if is first command in pipe sequence
#      to pass those to next pipe, but NOTE get ns | get .. is special case !!
#
# config get-contexts :
# - takes : nothing
# - provides: context, as column NAME
# api-resources:
# - takes context as #pipe
# - provides p_in['kind'] as column KIND:


import sys
import os
import subprocess
import signal
from stat import S_ISFIFO
import re

P_DEBUG = os.getenv(f"{PLUGIN_UNAME}_DEBUG")
P_SHORTCUT = os.getenv("KUBECTL_PLUGIN_SHORTCUT") or "_"

# TODO ensure passing more arguments
# all candidated for reconstruction (passing to right) currently only -n , --context are passed
# TODO kubeconfig is not passed , PIPE_KC_IN, or like PIPE_OPT_IN (cumulative for multiple passed options)
# TODO consider passing label selector across pipes , like PIPE_LL_IN for label

# TODO if those are passed and there are explicit --context -n  we should respect explicit
# TO TEST
# time /bin/bash -c " _ --context miku api-resources | _ get ns | _ get {{kind}} | _ get {{kind}} {{name}} > /tmp/x"
# time /bin/bash -c " _ --context miku api-resources | _ get {{kind}} -A | _ get {{kind}} {{name}} > /tmp/y"
#
# TO CONSIDER add command caching for fun
#
# TODO / TO FIX _ -n test-run top pod | _ sh echo \$LINE_NAM

def stream_helper():
    print("# Following execution streams are allowed:")
    print("# kc-inject -> config get-contexts")
    print("# config get-contexts -> api-resources")
    print("# config get-contexts -> get|plugin|exec|sh")
    print("# api-resources -> get|plugin|exec|sh")
    print("# get -> get|plugin|exec|sh")
    print("# get -> exec|plugin|exec|sh")

def int_signal_handler(sig, frame):
    print(f"Exit on Ctrl+C!")
    os.kill(os.getppid(), signal.SIGTERM)
    sys.exit(0)

def signal_ignore(sig, frame):
    pass

def term_signal_handler(sig, frame):
    sys.exit(0)

def detect_input():
    if sys.stdin.isatty():
        return "terminal"
    else:
        if S_ISFIFO(os.fstat(0).st_mode):
            return "fifo"
        else:
            return "pipe"

def detect_output():
    if sys.stdout.isatty():
        return "terminal"
    else:
        return "pipe"

def l_print_t(type,arg):
    print(f"#{PLUGIN_NAME}:{type}: {arg}",flush=True)

def l_print_e(type,arg):
    print(f"#{PLUGIN_NAME}:{type}: {arg}",flush=True,file=sys.stderr)

def available_plugins():
    plugins = []
    command = ["kubectl", "plugin", "list"]
    result = subprocess.run(command, capture_output=True, text=True, check=True)
    command_output = result.stdout
    lines = command_output.split("\n")
    for line in lines:
        if "/kubectl-" in line:
            offset = line.rindex("/kubectl-") + len("/kubectl-")
            plugins.append(line[offset:])
    return plugins

def set_pipe_input():
    p = {}
    for i in ['format','ctx','cmd','kind','nsed','name','ns','get','obj','kc']:
        p[i] = P_UNKNOWN
    return p

def set_cmd_input():
    cmd = {}
    for i in ['ctx','ns','kind','name','kc']:
        cmd[i] = P_UNKNOWN
    return cmd

def detect_in_plugin_content(pin,line):
    if line.startswith(f"#{PLUGIN_NAME}:{PIPE_CMD_IN}: "):
        pin['cmd'] = line[len(PLUGIN_NAME) + 4 + len(PIPE_CMD_IN):-1]
    elif line.startswith(f"#{PLUGIN_NAME}:{PIPE_FMT_IN}: "):
        pin['format'] = line[len(PLUGIN_NAME) + 4 + len(PIPE_FMT_IN):-1]
    elif line.startswith(f"#{PLUGIN_NAME}:{PIPE_NS_IN}: "):
        pin['ns'] = line[len(PLUGIN_NAME) + 4 + len(PIPE_NS_IN):-1]
    elif line.startswith(f"#{PLUGIN_NAME}:{PIPE_KIND_IN}: "):
        pin['kind'] = line[len(PLUGIN_NAME) + 4 + len(PIPE_KIND_IN):-1]
    elif line.startswith(f"#{PLUGIN_NAME}:{PIPE_CTX_IN}: "):
        pin['ctx'] = line[len(PLUGIN_NAME) + 4 + len(PIPE_CTX_IN):-1]
    elif line.startswith(f"#{PLUGIN_NAME}:{PIPE_NSED_IN}: "):
        pin['nsed'] = line[len(PLUGIN_NAME) + 4 + len(PIPE_NSED_IN):-1]
    elif line.startswith(f"#{PLUGIN_NAME}:{PIPE_KC_IN}: "):
        pin['kc'] = line[len(PLUGIN_NAME) + 4 + len(PIPE_KC_IN):-1]
    if pin['cmd'] == "get" and line.startswith(f"#{PLUGIN_NAME}:{PIPE_GET_IN}: "):
        pin['get'] = line[len(PLUGIN_NAME) + 4 + len(PIPE_GET_IN):-1]
    return pin

def read_header_line(line):
    position = []
    columns = []
    words = line.split()
    ofs = 0
    for idx in range(len(words)):
        pos = ofs + line[ofs:].index(words[idx])
        position.append(pos)
        columns.append(words[idx])
        ofs = pos + len(words[idx])
    return (position,columns)

def read_row_from_line(position,columns,line):
    content = {}
    if len(position):
        item = ""
        for idx in range(len(position)):
            if idx + 1 != len(position):
                item = line[position[idx]:position[idx + 1] - 1]
            else:
                item = line[position[idx]:-1]
            content[columns[idx]] = item.rstrip()
    return content

def fetch_kubectl_options():
    execArgs = ["kubectl", "options"]
    result = subprocess.run(execArgs, capture_output=True, text=True, check=True)
    command_output = result.stdout
    lines = command_output.split("\n")
    list = []
    for line in lines:
        left_part = line.split(':')[0]
        words = left_part.split()
        if len(words) > 0 and words[0][0] == '-':
            for word in words:
                if word[0] == "-" and word[0:2] != "--" and word[-1] == ",":
                    list.append(word[:-1])
                if word[0:2] == "--" and "=" in word:
                    list.append(word[:word.index('=')])
    return list

def fetch_kubectl_cmds():
    execArgs = ["kubectl"]
    result = subprocess.run(execArgs, capture_output=True, text=True, check=True)
    command_output = result.stdout
    lines = command_output.split("\n")
    list = []
    skip = False
    for line in lines:
        if line == "Subcommands provided by plugins:":
            skip = True
        if line == "Usage:":
            break
        if line == "":
            skip = False
        if skip:
            continue
        if line and line[-1] != ":" and line[:2] == "  ":
            words = line.split()
            list.append(words[0])
    return list

def fetch_kubectl_gettable_resources(context=""):
    if context:
        execArgs = ["kubectl", "--context", context, "api-resources", "--verbs=get,list", "--no-headers"]
    else:
        execArgs = ["kubectl", "api-resources", "--verbs=get,list", "--no-headers"]
    result = subprocess.run(execArgs, capture_output=True, text=True, check=True)
    command_output = result.stdout
    lines = command_output.split("\n")
    list = []
    for line in lines:
        sublist = []
        words = line.split()
        if len(words) == 5:
            sublist = words
        elif len(words) == 4:
            sublist = [words[0], "", words[1], words[2], words[3]]
        list.append(sublist)
    return list

def fetch_kubectl_cmd_options(cmd, context=""):
    if context:
        execArgs = ["kubectl", "--context", context, cmd, "-h"]
    else:
        execArgs = ["kubectl", cmd, "-h"]
    result = subprocess.run(execArgs, capture_output=True, text=True, check=True)
    command_output = result.stdout
    lines = command_output.split("\n")
    list = []
    skip = True
    for line in lines:
        if line == "Options:":
            skip = False
        if line == "Usage:":
            break
        if skip:
            continue
        left_part = line.split(':')[0]
        words = left_part.split()
        if len(words) > 0 and words[0][0] == '-':
            for word in words:
                if word[0] == "-" and word[0:2] != "--" and word[-1] == ",":
                    list.append(word[:-1])
                if word[0:2] == "--" and "=" in word:
                    list.append(word[:word.index('=')])
    return list

def system_exec(cmd):
    # os.system(cmd)
    # TO CONSIDER request caching !?
    if P_DEBUG:
        l_print_e(P_EXEC, f"{cmd}")
    execArgs = ["/bin/bash", "-c",cmd]
    try:
        result = subprocess.run(execArgs, capture_output=True, text=True, check=True)
        command_output = result.stdout
    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {e.cmd}")
        print(f"Return code: {e.returncode}")
        print(f"Standard output: {e.stdout}")
        print(f"Standard error: {e.stderr}")
        return
    lines = command_output.split("\n")
    for i in range(len(lines)):
        if i == len(lines) - 1 :
            print(lines[i],end="")
        else:
            print(lines[i])

def pass_output_format(args):
    outputPresent = "-o" in args[1:]
    if outputPresent:
        if len(args) > args[1:].index("-o") + 1:
            outputOptions = args[1:][args[1:].index("-o") + 1]
            l_print_t(PIPE_FMT_IN, f"{outputOptions}")
            return
    else:
        right_args = args[1:]
        for i in range(len(right_args)):
            if right_args[i].startswith("--options"):
                if '=' in right_args[i]:
                    eq_offset = right_args[i].index('=')
                    outputOptions = right_args[i][eq_offset+1 :]
                    l_print_t(PIPE_FMT_IN, f"{outputOptions}")
                    return
                elif len(right_args) > i + 1:
                    outputOptions = right_args[i+1]
                    l_print_t(PIPE_FMT_IN, f"{outputOptions}")
                    return
    l_print_t(PIPE_FMT_IN, f"{P_DEFAULT}")

def extract_get_options(context,extracted,kctlOpts):
    get_extracted = []
    if context == P_UNKNOWN:
        get_opts = fetch_kubectl_cmd_options("get")
    else:
        get_opts = fetch_kubectl_cmd_options("get",context=context)
    i = 0
    while i < len(extracted):
        if extracted[i] in get_opts:
            i += 2
            continue
        if "=" in extracted[i]:
            eq_index = extracted[i][:-1].index("=")
            if args[i][:eq_index] in kctlOpts:
                i += 1
                continue
        get_extracted.append(extracted[i])
        i += 1
    return get_extracted

def extract_args(args,cmd,kctlOpts):
    extracted = []
    extracted_args_position = []
    i = 0
    while i < len(args):
        if args[i] in kctlOpts:
            if args[i] in ['-n','--namespace'] and len(args) > i + 1:
                cmd['ns'] = args[i+1]
            if args[i] == '--context' and len(args) > i + 1:
                cmd['ctx'] = args[i+1]
            if args[i] == '--kubeconfig' and len(args) > i + 1:
                cmd['kc'] = args[i+1]
            i += 2
            continue
        if "=" in args[i][:-1]:
            eq_index = args[i][:-1].index("=")
            if args[i][:eq_index] in kctlOptions:
                if args[i][:eq_index] in ['-n','--namespace']:
                    cmd['ns'] = args[i][eq_index+1]
                if args[i][:eq_index] == '--context':
                    cmd['ctx'] = args[i][eq_index+1]
                if args[i][:eq_index] == '--kubeconfig':
                    cmd['kc'] = args[i][eq_index+1]
            i += 1
            continue
        if args[i][0:2] == "{{" and args[i][-2:] == "}}":
            i += 1
            continue
        if args[i] == P_SHORTCUT:
            i += 1
            continue
        extracted.append(args[i])
        extracted_args_position.append(i)
        i += 1
    return extracted,extracted_args_position,cmd

def generate_to_exec(p_in, toCheck):
        if p_in['ctx'] == P_UNKNOWN: # no ctx
            if p_in['kc'] == P_UNKNOWN: # no ctx, kc
                if p_in['nsed'] == 'false': # no ctx, no kc, no nsed
                    toExec = toCheck
                else: # nsed true
                    toExec = toCheck.replace(" _ ", " {{cns}} ")
                    toExec = toExec.replace("{{nsed}}", p_in['nsed'])
                    if p_in['ns'] != P_UNKNOWN and p_in['ns'] != "<none>":
                        toExec = toExec.replace("{{cns}}", p_in['ns'])
                        toExec = toExec.replace("{{ns}}", p_in['ns'])
                    else:
                        toExec = toExec.replace("{{cns}}","")
            else: # no ctx, kc
                if p_in['nsed'] == 'false':
                    toExec = toCheck.replace(" _ ", " {{ckc}} ")
                    toExec = toExec.replace("{{ckc}}", "--kubeconfig " + p_in['kc'])
                    toExec = toExec.replace("{{kc}}", p_in['kc'])
                else: # no ctx, kc, nsed true
                    toExec = toCheck.replace(" _ ", " {{ckc}} {{cns}} ")
                    toExec = toExec.replace("{{nsed}}", p_in['nsed'])
                    toExec = toExec.replace("{{ckc}}", "--kubeconfig " + p_in['kc'])
                    toExec = toExec.replace("{{kc}}", p_in['kc'])
                    if p_in['ns'] != P_UNKNOWN and p_in['ns'] != "<none>":
                        toExec = toExec.replace("{{cns}}", " -n " + p_in['ns'])
                        toExec = toExec.replace("{{ns}}", p_in['ns'])
                    else:
                        toExec = toExec.replace("{{cns}}","")
        else: # ctx
            if p_in['kc'] == P_UNKNOWN: # ctx, no kc
                if p_in['nsed'] == 'false': # ctx, no kc, no nsed
                    toExec = toCheck.replace(" _ ", " {{cctx}} ")
                    toExec = toExec.replace("{{cctx}}", "--context " + p_in['ctx'])
                    toExec = toExec.replace("{{ctx}}", p_in['ctx'])
                else: # ctx, no kc, nsed true
                    toExec = toCheck.replace(" _ ", " {{cctx}} {{cns}} ")
                    toExec = toExec.replace("{{nsed}}", p_in['nsed'])
                    toExec = toExec.replace("{{cctx}}", "--context " + p_in['ctx'])
                    toExec = toExec.replace("{{ctx}}", p_in['ctx'])
                    if p_in['ns'] != P_UNKNOWN and p_in['ns'] != "<none>":
                        toExec = toExec.replace("{{cns}}", " -n " + p_in['ns'])
                        toExec = toExec.replace("{{ns}}", p_in['ns'])
                    else:
                        toExec = toExec.replace("{{cns}}","")
            else: # ctx, kc
                if p_in['nsed'] == 'false':
                    toExec = toCheck.replace(" _ ", " {{ckc}} {{cctx}} ")
                    toExec = toExec.replace("{{ckc}}", "--kubeconfig " + p_in['kc'])
                    toExec = toExec.replace("{{kc}}", p_in['kc'])
                    toExec = toExec.replace("{{cctx}}", "--context " + p_in['ctx'])
                    toExec = toExec.replace("{{ctx}}", p_in['ctx'])
                else:
                    toExec = toCheck.replace(" _ ", " {{ckc}} {{cctx}} {{cns}} ")
                    toExec = toExec.replace("{{nsed}}", p_in['nsed'])
                    toExec = toExec.replace("{{ckc}}", "--kubeconfig " + p_in['kc'])
                    toExec = toExec.replace("{{kc}}", p_in['kc'])
                    toExec = toExec.replace("{{cctx}}", "--context " + p_in['ctx'])
                    toExec = toExec.replace("{{ctx}}", p_in['ctx'])
                    if p_in['ns'] != P_UNKNOWN and p_in['ns'] != "<none>":
                        toExec = toExec.replace("{{cns}}", " -n " + p_in['ns'])
                        toExec = toExec.replace("{{ns}}", p_in['ns'])
                    else:
                        toExec = toExec.replace("{{cns}}","")
        return toExec

def main_loop(args):
    global P_SHORTCUT
    all_cmds = fetch_kubectl_cmds()
    kctl_allowed = ["api-resources", "get", "config", "exec", "top"]
    prohibited = []
    for item in all_cmds:
        if item not in kctl_allowed:
            prohibited.append(item)

    kctlOptions = fetch_kubectl_options()
    internal = ["sh", "+", "-", "clean", "yaml-inject", "json-inject", "cgc","api-r", "kc-inject"]
    # TODO consider -O for _ formatting
    plugins = available_plugins()
    allowed = kctl_allowed + internal + plugins

    cmd = set_cmd_input()

    extracted,extracted_args_position,cmd = extract_args(args,cmd,kctlOptions)

    get_extracted = []
    if extracted[1] == "get":
        get_extracted = extract_get_options(cmd['ctx'], extracted,kctlOptions)
        if len(get_extracted) > 2:
            cmd['kind'] = get_extracted[2]
        if len(get_extracted) > 3:
            cmd['name'] = get_extracted[3]

    if not len(extracted) > 1:
        l_print_t(P_ERROR,"empty command or not recognized command")
        return -1

    command = extracted[1]
    if command in prohibited:
        l_print_t(P_ERROR,f"unhandled command {command}, prohibited")
        execArgs = ["kubectl"] + args[1:]
        system_exec(" ".join(execArgs))
        return -2

    if not command in allowed:
        l_print_t(P_ERROR,f"unhandled command {command}, not prohibited, not allowed")
        execArgs = ['kubectl'] + args[1:]
        print(execArgs)
        system_exec(" ".join(execArgs))
        return -3

    #all commands left are allowed
    position = []
    columns = []
    p_in = set_pipe_input()
    prev_p_in = set_pipe_input()
    if len(args) > extracted_args_position[1] + 1: # kind
        p_in['obj'] = args[extracted_args_position[1] + 1]
    line_num = 0
    prevLine = ""
    if (command == "config" and cmd['kind'] == "get-contexts") or command == "cgc":
        if detect_input() == "fifo":
            for line in sys.stdin:
                if prevLine:
                    line = prevLine + line
                if line[-1] != "\n":
                    prevLine = line
                    continue
                if line.startswith(f"#{PLUGIN_NAME}:"):
                    p_in = detect_in_plugin_content(p_in,line)
                    line_num = 0
                    continue
                else:
                    if p_in['cmd'] not in ["kc-inject",P_UNKNOWN]:
                        l_print_t(P_ERROR,
                            f"Illegal pipe pass: from {p_in['cmd']} to config_get-contexts"
                        )
                        stream_helper()
                        break
                    elif p_in['cmd'] in ["kc-inject",P_UNKNOWN]:  # command cgc, in kc-inject
                        if p_in['format'] == P_DEFAULT:
                            if line_num == 0 and line.isupper():
                                line_num += 1
                                position, columns = read_header_line(line)
                                continue
                            else: # loading fields
                                content = read_row_from_line(position, columns, line)
                                line_num += 1
                        elif p_in['format'] in ["name",P_UNKNOWN]:
                            p_in['ctx'] = line[:-1]
                            content['FILE'] = p_in['kc']
                        if detect_output() == "pipe":
                            l_print_t(PIPE_CMD_IN,"config_get-contexts")
                            if content['FILE'] != P_UNKNOWN:
                                l_print_t(PIPE_KC_IN,f"{content['FILE']}")
                            pass_output_format(args)
                        if command == "cgc":
                            if content['FILE'] != P_UNKNOWN:
                                execArgs = ["kubectl"] + ["--kubeconfig", content['FILE'], "config","get-contexts"] + args[2:]
                            else:
                                execArgs = ["kubectl"] + ['config','get-contexts'] + args[2:]
                        else:
                            if content['FILE'] != P_UNKNOWN:
                                execArgs = ["kubectl"] + ["--kubeconfig", content['FILE']] +  args[1:]
                            else:
                                execArgs = ["kubectl"] + args[1:]
                        system_exec(" ".join(execArgs))
        else:
            if detect_output() == "pipe":
                l_print_t(PIPE_CMD_IN, "config_get-contexts")
                pass_output_format(args)
            if command == "cgc":
                execArgs = ["kubectl"] + ['config', 'get-contexts'] + args[2:]
            else:
                execArgs = ["kubectl"] + args[1:]
            system_exec(" ".join(execArgs))
    elif command == "kc-inject":
        if detect_input() == "fifo":
            l_print_e(P_WARNING, f"Illegal pipe pass: to config get-contexts, ignored")
        else:
            if detect_output() == "pipe":
                l_print_t(PIPE_CMD_IN, f"{command}")
            pass_output_format(args)
            out_list = []
            for i in args[2:]:
                if os.path.exists(i):
                    out_list.append(i)
                else:
                    l_print_e(P_WARNING,f"file {i} does note exist")
            if out_list:
                print("FILE")
            for i in out_list:
                print(i)
    elif command in ["+", "-"]:# TODO convert to new format
        if detect_input() == "fifo":
            for line in sys.stdin:
                if prevLine:
                    line = prevLine + line
                if line[-1] != "\n":
                    prevLine = line
                    continue

                if line[0:len(PLUGIN_NAME) + 2] == f"#{PLUGIN_NAME}:":
                    print(line, end="")
                else:
                    if args[1] == "-":
                        match = False
                        for i in args[2:]:
                            if re.search(i, line):
                                match = True
                        if not match:
                            print(line, end="")
                    elif args[1] == "+":
                        for i in args[2:]:
                            if re.search(i, line):
                                print(line, end="")
                                break
        else:
            l_print_t(P_ERROR,f"no pipe input for {command}")
    elif command == 'clean':
        if cmd['kind'] == "headers":
            for line in sys.stdin:
                if not line.isupper() and not line.startswith(f"#{PLUGIN_NAME}:"):
                    print(line,end="")
       # TODO additional clean arguments like clean columns
       #  elif cmd['kind'] == "columns": # TODO
       #      columns_to_clean = extracted[3:]
       #      line_num = 0
       #      for line in sys.stdin:
       #          if line_num == 0 and line.isupper():
       #              line_num += 1
       #              continue
       #          else:  # loading fields
       #              content = read_row_from_line(position, columns,line)
       #              line_num += 1
        else:
            for line in sys.stdin:
                if not line.startswith(f"#{PLUGIN_NAME}:"):
                    print(line, end="")
    elif command == "yaml-inject":
        plugin_content = True
        for line in sys.stdin:
            if line.startswith(f"#{PLUGIN_NAME}:"):
                plugin_content = True
                if line.startswith(f"#{PLUGIN_NAME}:{PIPE_CTX_IN}: "):
                    p_in = detect_in_plugin_content(p_in,line)
            else:
                if plugin_content and p_in['ctx'] != P_UNKNOWN:
                    print(f"---\ncontext: {p_in['ctx']}\n", end="")
                plugin_content = False
                print(line, end="")
    elif command == 'json-inject':
        inject = ""
        plugin_content = True
        line = sys.stdin.readline()
        while line:
            newline = sys.stdin.readline()
            if line.startswith(f"#{PLUGIN_NAME}:"):
                plugin_content = True
                if line.startswith(f"#{PLUGIN_NAME}:{PIPE_CTX_IN}: "):
                    p_in = detect_in_plugin_content(p_in, line)
                    if p_in['ctx'] != P_UNKNOWN:
                        inject = '"context": "' + p_in['ctx'] + '",'
            else:  ## TODO check json ident comparing to jq
                if line == "{\n" and inject:
                    print("{\n    " + inject)
                elif line == "}\n":
                    if newline:
                        print(line[:-1])
                    else:
                        print(line[:-1])
                else:
                    print(line, end="")
            line = newline
    elif command in ["get","sh","exec","top"] + plugins:  # in cmd command
        if detect_input() == "fifo":
            for line in sys.stdin:
                if prevLine:
                    line = prevLine + line
                if line[-1] != "\n":
                    prevLine = line
                    continue
                if line.startswith(f"#{PLUGIN_NAME}:"):
                    p_in = detect_in_plugin_content(p_in,line)
                    line_num = 0
                    continue
                else:
                    if p_in['cmd'] not in ["config_get-contexts","get","api-resources","sh","exec","top",P_UNKNOWN] \
                            and not p_in['cmd'].startswith("plugin:"):
                        l_print_t(P_ERROR,
                            f"Illegal pipe pass: from {p_in['cmd']} to {command}"
                        )
                        stream_helper()
                        break
                    elif p_in['cmd'] == "config_get-contexts":  # command get, cgc
                        if p_in['format'] == P_DEFAULT:
                            if line_num == 0 and line.isupper():
                                line_num += 1
                                position, columns = read_header_line(line)
                                continue
                            else: # loading fields
                                content = read_row_from_line(position, columns, line)
                                line_num += 1
                        elif p_in['format'] in ["name",P_UNKNOWN]:
                            p_in['ctx'] = line[:-1]
                            content['NAME'] = p_in['ctx']
                        if 'cmd' in p_in and p_in['cmd'] != P_UNKNOWN and 'IN_CMD' not in content:
                            content['IN_CMD'] = p_in['cmd']
                        if 'NAME' in content:
                            p_in['ctx'] = content['NAME']
                        if command == 'sh':
                            toCheck = " ".join(args[2:])
                            for item in content:
                                os.environ[f"{PLUGIN_UNAME}_{item}"] = content[item]
                        elif args[0].split("/")[-1] == P_SHORTCUT:
                            toCheck = " ".join(["kubectl", P_SHORTCUT] + args[1:])
                        else:
                            toCheck = " ".join(["kubectl"] + args[1:])
                        toExec = generate_to_exec(p_in, toCheck)
                        if detect_output() == "pipe": # command get, in cgc
                            l_print_t(PIPE_CMD_IN, f"{command}")
                            if p_in['ns'] != P_UNKNOWN and prev_p_in['ns'] != p_in['ns']:
                                l_print_t(PIPE_NS_IN,f"{p_in['ns']}")
                                prev_p_in['ns'] = p_in['ns']
                            if p_in['ctx'] != P_UNKNOWN and prev_p_in['ctx'] != p_in['ctx']:
                                l_print_t(PIPE_CTX_IN,f"{p_in['ctx']}")
                                prev_p_in['ctx'] = p_in['ctx']
                            if p_in['kind'] != P_UNKNOWN and prev_p_in['kind'] != p_in['kind']:
                                l_print_t(PIPE_KIND_IN,f"{p_in['kind']}")
                                prev_p_in['kind'] = p_in['kind']
                            if p_in['kc'] != P_UNKNOWN:
                                l_print_t(PIPE_KC_IN, f"{p_in['kc']}")
                        for item in content:
                            toExec = toExec.replace("{{"+item+"}}", content[item])
                        system_exec(toExec)
                    elif p_in['cmd'] == "get":  # in cmd get, prev get
                        if p_in['format'] in [P_DEFAULT, "wide"]:
                            if line_num == 0 and line.isupper():
                                line_num += 1
                                position, columns = read_header_line(line)
                                continue
                            else:
                                content = read_row_from_line(position, columns, line)
                                line_num += 1
                            if line_num > 2 and p_in['nsed'] == 'false' and p_in['get'] == "ns":
                                continue
                            if 'cmd' in p_in and p_in['cmd'] != P_UNKNOWN and 'IN_CMD' not in content:
                                content['IN_CMD'] = p_in['cmd']
                            p_in['name'] = P_UNKNOWN
                            if p_in['cmd'] != P_UNKNOWN:
                                if 'NAME' in content:
                                    if p_in['kind'] in ['ns','namespace']: # TODO issue ns vs namespace,
                                        content['NAMESPACE'] = content['NAME']
                                        content['NS'] = content['NAME']
                                    else:
                                        content[p_in['get'].upper()] = content['NAME']
                                    p_in['name'] = content['NAME']
                                if 'KIND' not in content and p_in['kind'] != P_UNKNOWN:
                                    content['KIND'] = p_in['kind'] # TODO separate pipe_p_in['kind'] from p_in['kind']
                            if 'KIND' in content:  # override value from pipe
                                p_in['kind'] = content['KIND']
                            if 'NAME' in content: # fixing kubectl non standard output for storageClass
                                if p_in['kind'] == 'StorageClass' and ' (default)' in content['NAME']:
                                    p_in['name'] = content['NAME'][0:-10]
                                else:
                                    p_in['name'] = content['NAME']
                            if 'NAMESPACE' in content:
                                p_in['ns'] = content['NAMESPACE']
                        elif p_in['format'] == "name":  # name does not support kind, nsed
                            l_print_t(P_ERROR,f"get format name not supported")
                            break
                        if command == 'sh':
                            toCheck = " ".join(args[2:])
                            for item in content:
                                os.environ[f"{PLUGIN_UNAME}_{item}"] = content[item]
                        elif args[0].split("/")[-1] == P_SHORTCUT:
                            toCheck = " ".join(["kubectl", P_SHORTCUT] + args[1:])
                        else:
                            toCheck = " ".join(["kubectl"] + args[1:])
                        toExec = generate_to_exec(p_in, toCheck)
                        toExec = toExec.replace("{{name}}", p_in['name'])
                        toExec = toExec.replace("{{kind}}", p_in['kind'])
                        if detect_output() == "pipe": # command get, in get
                            l_print_t(PIPE_CMD_IN, f"{command}")
                            if p_in['ns'] != P_UNKNOWN and prev_p_in['ns'] != p_in['ns']:
                                l_print_t(PIPE_NS_IN,f"{p_in['ns']}")
                                prev_p_in['ns'] = p_in['ns']
                            if p_in['ctx'] != P_UNKNOWN and prev_p_in['ctx'] != p_in['ctx']:
                                l_print_t(PIPE_CTX_IN,f"{p_in['ctx']}")
                                prev_p_in['ctx'] = p_in['ctx']
                            if p_in['kind'] != P_UNKNOWN and prev_p_in['kind'] != p_in['kind']:
                                l_print_t(PIPE_KIND_IN,f"{p_in['kind']}")
                                prev_p_in['kind'] = p_in['kind']
                            if p_in['kc'] != P_UNKNOWN:
                                l_print_t(PIPE_KC_IN, f"{p_in['kc']}")
                            execWords = toExec.split()
                            noheaderPresent = "--no-headers" in execWords
                            pass_output_format(args)
                            # if unusual output is used then force headers ie remove no-headers
                            if noheaderPresent:
                                toExec = toExec.replace("--no-headers", "")
                        for item in content:
                            toExec = toExec.replace("{{"+item+"}}", content[item])
                        system_exec(toExec)
                    elif p_in['cmd'] == "api-resources":  # in cmd get
                        if p_in['format'] in [P_DEFAULT, "wide"]:
                            if line_num == 0 and line.isupper():
                                line_num += 1
                                position, columns = read_header_line(line)
                                continue
                            else:
                                content = read_row_from_line(position, columns, line)
                                line_num += 1
                            if 'cmd' in p_in and p_in['cmd'] != P_UNKNOWN and 'IN_CMD' not in content:
                                content['IN_CMD'] = p_in['cmd']
                            p_in['name'] = P_UNKNOWN
                            if 'NAME' in content:
                                p_in['name'] = content['NAME']
                            p_in['kind'] = P_UNKNOWN
                            if 'KIND' in content:
                                p_in['kind'] = content['KIND']
                            p_in['nsed'] = P_UNKNOWN
                            if 'NAMESPACED' in content:
                                p_in['nsed'] = content['NAMESPACED']
                        elif p_in['format'] == "name":  # name does not support kind, nsed
                            l_print_t(P_ERROR,f"api-resources format name not supported")
                            break
                        if command == 'sh':
                            toCheck = " ".join(args[2:])
                            for item in content:
                                os.environ[f"{PLUGIN_UNAME}_{item}"] = content[item]
                        elif args[0].split("/")[-1] == P_SHORTCUT:
                            toCheck = " ".join(["kubectl", P_SHORTCUT] + args[1:])
                        else:
                            toCheck = " ".join(["kubectl"] + args[1:])
                        toExec = generate_to_exec(p_in, toCheck)
                        if p_in['kind'] != P_UNKNOWN:
                            toExec = toExec.replace("{{kind}}", p_in['kind'])
                        if p_in['name'] != P_UNKNOWN:
                            toExec = toExec.replace("{{name}}", p_in['name'])
                        if detect_output() == "pipe": # command get , in api-r
                            if p_in['cmd'] != P_UNKNOWN and prev_p_in['cmd'] != p_in['cmd']:
                                l_print_t(PIPE_CMD_IN,f"{command}")
                                prev_p_in['cmd'] = p_in['cmd']
                            if p_in['obj'] != P_UNKNOWN and p_in['obj'] != '{{kind}}' and prev_p_in['obj'] != p_in['obj']:
                                l_print_t(PIPE_GET_IN,f"{p_in['obj']}")
                                prev_p_in['obj'] = p_in['obj']
                            if p_in['ctx'] != P_UNKNOWN and prev_p_in['ctx'] != p_in['ctx']:
                                l_print_t(PIPE_CTX_IN,f"{p_in['ctx']}")
                                prev_p_in['ctx'] = p_in['ctx']
                            if p_in['ns'] != P_UNKNOWN and prev_p_in['ns'] != p_in['ns']:
                                l_print_t(PIPE_NS_IN,f"{p_in['ns']}")
                                prev_p_in['ns'] = p_in['ns']
                            if p_in['nsed'] != P_UNKNOWN and prev_p_in['nsed'] != p_in['nsed']:
                                l_print_t(PIPE_NSED_IN,f"{p_in['nsed']}")
                                prev_p_in['nsed'] = p_in['nsed']
                            if p_in['kind'] != P_UNKNOWN and prev_p_in['kind'] != p_in['kind']:
                                l_print_t(PIPE_KIND_IN,f"{p_in['kind']}")
                                prev_p_in['kind'] = p_in['kind']
                            if p_in['kc'] != P_UNKNOWN:
                                l_print_t(PIPE_KC_IN, f"{p_in['kc']}")
                            pass_output_format(args) # TO CONSIDER should w tack prev_p_in['format']
                        for item in content:
                            toExec = toExec.replace("{{"+item+"}}", content[item])
                        system_exec(toExec)
                    else:  # command get : unknown in cmd, best effort
                        if line_num == 0 and line.isupper():
                            line_num += 1
                            position, columns = read_header_line(line)
                            continue
                        elif line_num == 0 and p_in['cmd'] == "top":
                            line_num += 1
                            modified_line = line.upper()
                            modified_line = modified_line.replace('(','')
                            modified_line = modified_line.replace(')', '')
                            position, columns = read_header_line(modified_line)
                            continue
                        else:  # loading fields
                            content = read_row_from_line(position, columns, line)
                            line_num += 1
                        if 'cmd' in p_in and p_in['cmd'] != P_UNKNOWN and 'IN_CMD' not in content:
                            content['IN_CMD'] = p_in['cmd']
                        if 'CONTEXT' in content:
                            p_in['ctx'] = content['CONTEXT']
                        if 'NAMESPACE' in content:
                            p_in['ns'] = content['NAMESPACE']
                        if 'KIND' in content:
                            p_in['kind'] = content['KIND']
                        if 'NAME' in content:
                            p_in['name'] = content['NAME']
                        if p_in['ctx'] == P_UNKNOWN and p_in['ns'] == P_UNKNOWN and p_in['kind'] == P_UNKNOWN and p_in['name'] == P_UNKNOWN:
                            # cmd get : no recognized format, best effort failed
                            l_print_t(P_ERROR,
                                f"not enough input: CONTEXT, NAMESPACE, KIND, NAME"
                            )
                            break
                        else:
                            if command == 'sh':
                                toCheck = " ".join(args[2:])
                                for item in content:
                                    os.environ[f"{PLUGIN_UNAME}_{item}"] = content[item]
                            elif args[0].split("/")[-1] == P_SHORTCUT:
                                toCheck = " ".join(["kubectl", P_SHORTCUT] + args[1:])
                            else:
                                toCheck = " ".join(["kubectl"] + args[1:])
                            toExec = generate_to_exec(p_in, toCheck)
                            if p_in['name'] != '<none>' and p_in['name'] != P_UNKNOWN:
                                toExec = toExec.replace("{{name}}",p_in['name'])
                            if p_in['kind'] != '<none>' and p_in['kind'] != P_UNKNOWN:
                                toExec = toExec.replace("{{kind}}", p_in['kind'])
                            if detect_output() == "pipe": # command get, no in cmd
                                l_print_t(PIPE_CMD_IN,f"{command}")
                                if p_in['ns'] != P_UNKNOWN and prev_p_in['ns'] != p_in['ns']:
                                    l_print_t(PIPE_NS_IN,f"{p_in['ns']}")
                                    prev_p_in['ns'] = p_in['ns']
                                if p_in['ctx'] != P_UNKNOWN and prev_p_in['ctx'] != p_in['ctx']:
                                    l_print_t(PIPE_CTX_IN,f"{p_in['ctx']}")
                                    prev_p_in['ctx'] = p_in['ctx']
                                if p_in['kind'] != P_UNKNOWN and prev_p_in['kind'] != p_in['kind']:
                                    l_print_t(PIPE_KIND_IN,f"{p_in['kind']}")
                                    prev_p_in['kind'] = p_in['kind']
                                if p_in['kc'] != P_UNKNOWN:
                                    l_print_t(PIPE_KC_IN,f"{p_in['kc']}")
                                execWords = toExec.split()
                                noheaderPresent = "--no-headers" in execWords
                                pass_output_format(args)
                                if noheaderPresent:
                                    toExec = toExec.replace("--no-headers", "")
                            for item in content:
                                toExec = toExec.replace("{{" + item + "}}", content[item])
                            system_exec(toExec)
                        break
        else:  # command get, no input pipe
            if detect_output() == "pipe":
                if command in plugins:
                    l_print_t(PIPE_CMD_IN,f"plugin:{command}")
                else:
                    l_print_t(PIPE_CMD_IN, f"{command}")
                if cmd['ctx'] != P_UNKNOWN:
                    l_print_t(PIPE_CTX_IN,f"{cmd['ctx']}")
                # TODO cmd['ns'] not needed if get ns is used
                if cmd['kind'] != P_UNKNOWN:
                    l_print_t(PIPE_KIND_IN,f"{cmd['kind']}")
                if cmd['name'] != P_UNKNOWN:
                    l_print_t(PIPE_NAME_IN,f"{cmd['name']}")
                if cmd['kc'] != P_UNKNOWN:
                    l_print_t(PIPE_KC_IN, f"{cmd['kc']}")
                # TODO pass label selectors
                pass_output_format(args)
                execArgs = (
                        ["kubectl"]
                        + args[1:]
                )
            else:  # cmd get/plugin/sh, no input pipe, no output pipe, just exec command
                execArgs = ["kubectl"] + args[1:]
            system_exec(" ".join(execArgs))
    elif command in ["api-resources","api-r"]:  # cmd api-resources
        if command == "api-r":
            args[1] = "api-resources"
            command = "api-resources"
        if detect_input() == "fifo":
            for line in sys.stdin:
                if prevLine:
                    line = prevLine + line
                if line[-1] != "\n":
                    prevLine = line
                    continue
                if line.startswith(f"#{PLUGIN_NAME}:"):
                    p_in = detect_in_plugin_content(p_in,line)
                    line_num = 0
                    continue
                else:
                    if p_in['cmd'] not in ["config_get-contexts",P_UNKNOWN]:
                        l_print_t(P_ERROR,
                            f"Illegal pipe pass: from {p_in['cmd']} to api-resources"
                        )
                        stream_helper()
                        break
                    elif p_in['cmd'] == "config_get-contexts":  # command api-r
                        if p_in['format'] == P_DEFAULT:
                            # loading headers
                            if line_num == 0 and line.isupper():
                                line_num += 1
                                position, columns = read_header_line(line)
                                continue
                            else: # loading fields
                                content = read_row_from_line(position, columns, line)
                                line_num += 1
                                if 'NAME' in content:
                                    p_in['ctx'] = content['NAME']
                        elif p_in['format'] == "name":
                            p_in['ctx'] = line[:-1]
                        toCheck = ""
                        if args[0].split("/")[-1] == P_SHORTCUT:
                            toCheck = " ".join(["kubectl", P_SHORTCUT] + args[1:])
                        else:
                            toCheck = " ".join(["kubectl"] + args[1:])
                        toExec = generate_to_exec(p_in, toCheck)
                        if detect_output() == "pipe": # command api-r, in cgc
                            l_print_t(PIPE_CMD_IN,f"{command}")
                            if p_in['ctx'] != P_UNKNOWN:
                                l_print_t(PIPE_CTX_IN, f"{p_in['ctx']}")
                            if cmd['ns'] != P_UNKNOWN:
                                l_print_t(PIPE_NS_IN,f"{cmd['ns']}")
                            if p_in['kc'] != P_UNKNOWN:
                                l_print_t(PIPE_KC_IN, f"{p_in['kc']}")
                            pass_output_format(args)
                            l_print_t(PIPE_NOTE_IN,f"appending --verbs=get,list")
                            toExec = toExec + " --verbs=get,list"
                        for item in content:
                            toExec = toExec.replace("{{"+item+"}}", content[item])
                        system_exec(toExec)
                    else:  # command api resources,  no in cmd, best effort
                        if detect_input() == "fifo":
                            if prevLine:
                                line = prevLine + line
                            if line[-1] != "\n":
                                prevLine = line
                                continue
                            if line_num == 0 and line.isupper():
                                line_num += 1
                                position, columns = read_header_line(line)
                                continue
                            else:
                                content = read_row_from_line(position, columns, line)
                                line_num += 1
                            if 'NAME' in content:
                                p_in['ctx'] = content['NAME']
                            # if context is explicit column, we override context from name
                            # context can be generated with some other tool or formated file
                            if 'CONTEXT' in content:
                                p_in['ctx'] = content['CONTEXT']
                            ### TODO custom kind of input anything can be replaced no error is printed
                            if p_in['ctx'] == P_UNKNOWN:  # taking line as context name
                                p_in['ctx'] = line[:-1]
                            toCheck = ""
                            if args[0].split("/")[-1] == P_SHORTCUT:
                                toCheck = " ".join(["kubectl", P_SHORTCUT] + args[1:])
                            else:
                                toCheck = " ".join(["kubectl"] + args[1:])
                            toExec = generate_to_exec(p_in, toCheck)
                            if detect_output() == "pipe": # command api-r, no in cmd
                                l_print_t(PIPE_CMD_IN,f"{command}")
                                if p_in['ctx'] != P_UNKNOWN:
                                    l_print_t(PIPE_CTX_IN,f"{p_in['ctx']}")
                                if p_in['kc'] != P_UNKNOWN:
                                    l_print_t(PIPE_KC_IN,f"{p_in['kc']}")
                                pass_output_format(args)
                                l_print_t(PIPE_NOTE_IN,f"appending --verbs=get,list")
                                toExec = toExec + " --verbs=get,list"
                            for item in content:
                                toExec = toExec.replace("{{" + item + "}}", content[item])
                            system_exec(toExec)
                    line_num += 1
        else:  #  command api-resources, detect input is not fifo
            if detect_output() == "pipe":
                l_print_t(PIPE_CMD_IN,f"{command}")
                if cmd['ctx'] != P_UNKNOWN:
                    l_print_t(PIPE_CTX_IN,f"{cmd['ctx']}")
                if cmd['ns'] != P_UNKNOWN:
                    l_print_f(PIPE_NS_IN,f"{cmd['ns']}")
                if cmd['kind'] != P_UNKNOWN:
                    l_print_t(PIPE_KIND_IN,f"{cmd['kind']}")
                if cmd['name'] != P_UNKNOWN:
                    l_print_t(PIPE_NAME_IN,f"{cmd['name']}")
                pass_output_format(args)
                l_print_t(PIPE_NOTE_IN,f"appending --verbs=get,list")
                execArgs = (
                        ["kubectl"]
                        + args[1:]
                        + ["--verbs=get,list"]
                )
            else:  # cmd api resources no input pipe, no output pipe, just execute
                execArgs = ["kubectl"] + args[1:]
            system_exec(" ".join(execArgs))
    else:  # no command recognized
        if command != "config": # otherwise we have command that we cover completely
            l_print_t(P_WARNING,f"unhandled command, trying default kubectl {command}")
            execArgs = args[1:]
            system_exec(" ".join(execArgs))
        else:
            l_print_t(P_WARNING,
                f"unrecognized command {command}, not prohibited, not allowed"
            )
            execArgs = args[1:]
            system_exec(" ".join(execArgs))
    return 0

signal.signal(signal.SIGINT, int_signal_handler)
signal.signal(signal.SIGTERM, term_signal_handler)

if __name__ == '__main__':
    sys.exit(main_loop(sys.argv))
